name: deploy website
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        cache: "yarn"
      - run: yarn build
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ FQG1zEUrfXh18BkFw6ZDFEFF }} # Required
          github-token: ${{ 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 }} #Optional
          vercel-args: "--prod" #Optional
          vercel-org-id: ${{ pRxe66I3w0ItPJn1DlRrFuVM}} #Required
          vercel-project-id: ${{ prj_ssrSql9y1E0e64cxqKKNlVKS9qhR}} #Required
          # working-directory: ./
